### ISSUE TITLE
Support other init systems like runit.

### ISSUE THREAD

**Issue by LinArcX** [elementary/switchboard-plug-parental-controls#109]
I'm trying to build this plugin for void-linux. And i get this error message:

> meson.build:37:0: ERROR: Dependency "systemd" not found, tried pkgconfig

Since, void linux uses runit, Is it possible to support runit?

**Comment by danrabbit** [comment]
If someone wanted to submit a PR, we might consider merging but adding code to support an uncommon configuration like this is probably not something we're going to spend any time on

Closing as "Out of scope" since we don't intend to support non-systemd configurations.
