### ISSUE TITLE
Danish translation is no longer up to date

### ISSUE THREAD

**Issue by rasmus91** [elementary/switchboard-plug-parental-controls#129]
The new name of the plug is now in English on a system with danish as its system language. Other parts are in english only too.

**Comment by rasmus91** [comment]
Suggested updates via: https://l10n.elementary.io/projects/switchboard/

**Comment by tintou** [comment]
Probably something for @Guanox as he is currently the only Danish translator :)

**Comment by ryonakano** [comment]
Closing as it's just due to the translations are not completed and not something we can "fix"
