### ISSUE TITLE
Block one flatpak application causes all flatpak applications to blocks

### ISSUE THREAD

**Issue by TheRock892** [elementary/switchboard-plug-parental-controls#139]
If I block a flatpak application, all flatpak applications disappear and become unexecutable both from the applications menu (they are still visible on the dock) and become inaccessible even from the terminal.

Even the flatpak executable is inaccessible from the terminal!

**Comment by cassidyjames** [comment]
Hm that indeed seems problematic. I would guess this is because the `Exec` command in the .desktop starts with `Exec=/usr/bin/flatpak run`, so this ends up blocking the Flatpak binary.

**Comment by davidmhewitt** [comment]
I think the easiest way to fix this would be to start looking into malcontent integration.

I've started work on getting that packaged for Odin in os-patches, issue tracking that here: https://github.com/elementary/os-patches/issues/147
