### ISSUE TITLE
compiling without using systemd

### ISSUE THREAD

**Issue by alihanozturk** [elementary/switchboard-plug-parental-controls#161]
### Problem

I want to compile this package by excluding systemd but systemd option is not given in meson options. How do I compile the switchboard-plug-parental-controls package on systems that don't use systemd. Which options should I use in configure?

### Proposal

I want to compile without systemd

**Comment by tintou** [comment]
We are targeting systemd, but patches welcome

**Comment by alihanozturk** [comment]
If you put a systemd option like in the gala/meson_options.txt file, wouldn't it be better if we compile it without systemd with the command at the meson.configure stage?

**Comment by alihanozturk** [comment]
> We are targeting systemd, but patches welcome

Nasıl bir patch yapmam gerekecek acaba.

**Comment by danrabbit** [comment]
I'm inclined to close this as "Design conflict". We require systemd in Pantheon and we're increasingly relying on its existence in other components. I don't think it makes sense to try to maintain components for a non-systemd session
