### ISSUE TITLE
Package building fail with debhelper >= 10.9.2

### ISSUE THREAD

**Issue by gandalfn** [elementary/switchboard-plug-parental-controls#32]
debian/rules use debhelper dh_systemd_<enable/start> to install  systemd pantheon-parental-controls.service with -p option to specify the package which own service. 

Currently the name of the service has been passed to this option instead of package name, according debhelper man page. 

Since debhelper >= 10.9.2 the package building failed.

**Comment by danrabbit** [comment]
Fixed by #33

**Comment by danrabbit** [comment]
Fixed by #33
