### ISSUE TITLE
Parental Controls not working at all

### ISSUE THREAD

**Issue by erakare** [elementary/switchboard-plug-parental-controls#71]
I tried it with two computers, but they are not working at all.
Websites are not blocked when I block them, and I can still open blocked applications.

I made it double clear that my settings were right e.g that my testing account was a normal account and the other an administrator in which I used the parental controlls application.

Since this is a flagship feature, the priority should be high, but the cause of the issue is unknown.

**Comment by danrabbit** [comment]
Closing as a duplicate of #55
