### ISSUE TITLE
Clarify time limits are for when the user is allowed to use the computer

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-parental-controls#94]
Right now I think it can be confusing as to whether the user is being restricted to **not** use the computer during those times, or to **only** use the computer during those times. It turns out it's the latter, and we should make that more clear.

**Comment by 4jNsY6fCVqZv** [comment]
How does it behave, if I am the only user of the system and therefore also admin? Does this mean that in case of an emergency I really can't get back into the system outside the selected time period? I'd like a little more clarity on this!

**Comment by danrabbit** [comment]
Fixed in the latest release

**Comment by 4jNsY6fCVqZv** [comment]
> Fixed in the latest release

Regarding Cassidy's concern or my question part of the issue as well?
